Feature/345 inversion solution nrml objects
GNS-Science/simple-toshi-ui pull request #351
Opened 2022-04-19 22:41 UTC by 0qy

2022-04-19 23:47 UTC, benjamineac approved these changes

2022-04-20 22:22 UTC, chrisdicaprio approved these changes

2022-04-20 22:29 UTC, chrisdicaprio requested changes
@0qy the InversionSolution ID as a navlink dosn't change depending on type (`ScaledInversionSolution` vs `InversionSolution`). Results in ID not found if type is `ScaledInversionSolution`

2022-04-21 03:08 UTC, chrisbc commented
> @0qy the InversionSolution ID as a navlink dosn't change depending on type (`ScaledInversionSolution` vs `InversionSolution`). Results in ID not found if type is `ScaledInversionSolution`

@0qy and I looked at this and the problem is the data . the InvSol ID has been saved in API instead of the ScaledIS. See [new Runzi ticket](https://github.com/GNS-Science/nzshm-runzi/issues/103)

2022-04-26 21:09 UTC, chrisbc commented
@chrisdicaprio can you give your approval on this one pls? (following our discussion re runzi data / ticket )

2022-04-28 03:15 UTC, chrisdicaprio requested changes
fix typo

2022-04-28 03:15 UTC, chrisdicaprio commented on src/pages/InversionSolutionNrml.tsx
> +            <a href={data?.node?.file_url ?? ''}>Downlaod</a>
typo "Download"

2022-04-28 03:41 UTC, chrisdicaprio approved these changes

2022-04-28 03:52 UTC, merged