Feature/337 mfd missing points
GNS-Science/simple-toshi-ui pull request #352
Opened 2022-04-19 23:02 UTC by benjamineac

Fixes missing data points not showing on dynamic MFDs for GeneralViewMfd and InversionSolutionMfdTab;

2022-04-20 21:16 UTC, 0qy commented on src/components/diagnosticReportView/GeneralViewMfd.tsx
> +  console.log(data);
remove console.log

2022-04-20 21:27 UTC, benjamineac commented on src/components/diagnosticReportView/GeneralViewMfd.tsx
> +  console.log(data);
👍

2022-04-20 22:07 UTC, chrisdicaprio approved these changes

2022-04-20 22:40 UTC, chrisbc requested changes
@benjamineac as discussed this can be greatly simplified by...

 - assume that MFD series points should never skip points and are on regular interval 0.1 (something in opensha is missing these points, so this is a 'UI workaround' )
 - safe to 'fill all` from 5.05 (minimim) to 9.95 (maxima) as this covers all values 
 - use default value of 1e-20
 - apply this transform to all MFD series

2022-04-25 21:47 UTC, chrisbc approved these changes

2022-04-25 22:19 UTC, merged